Ce que vous apprendrez :
Les opérations principales de NumPy incluent la création et la manipulation de tableaux et les opérations basiques du tableau.
Compétences dans la gestion de réseaux unidimensionnels et multidimensionnels.


Ce que vous allez créer :
Une série de tableaux NumPy démontrant différentes opérations, allant de la simple création de tableaux à des manipulations plus complexes.


🌟 Exercice 1 : Création et manipulation de réseaux
Instructions
Créez un tableau NumPy 1D contenant des nombres de 0 à 9.

Résultats attendus :



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


🌟 Exercice 2 : Conversion de type et opérations sur l’array
Instructions
Convertissez une liste en tableau NumPy et convertissez son type de données en entier.[3.14, 2.17, 0, 1, 2]

Résultats attendus :



array([3, 2, 0, 1, 2])


🌟 Exercice 3 : Travailler avec des réseaux multidimensionnels
Instructions
Créez un tableau NumPy 3x3 avec des valeurs allant de 1 à 9.

Résultats attendus :



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


🌟 Exercice 4 : Créer un tableau multidimensionnel avec des nombres aléatoires
Instructions
Créez un tableau NumPy 2D de formes (4, 5) remplies de nombres aléatoires.

Résultats attendus :



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])


🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])


🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5


🌟 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


🌟 Exercice 10 : Sélection conditionnelle des valeurs
Instructions
Extraire tous les nombres impairs d’un tableau NumPy donné.

Résultats attendus :



array([1, 3, 5, 7, 9])


Soumettez vos exercices :
N’oublie pas de pousser pour Github

In [1]:
import numpy as np

In [2]:
# Créer un tableau 1D de 0 à 9
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Convertir une liste en tableau NumPy avec le type entier
liste = [3.14, 2.17, 0, 1, 2]
array_int = np.array(liste, dtype=int)
print(array_int)

[3 2 0 1 2]


In [4]:
# Créer un tableau 3x3 avec des valeurs de 1 à 9
array_3x3 = np.arange(1, 10).reshape(3, 3)
print(array_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Créer un tableau 2D (4, 5) de nombres aléatoires arrondis à 2 décimales
array_random = np.round(np.random.rand(4, 5), 2)
print(array_random)

[[0.83 0.65 0.7  0.08 0.14]
 [0.41 0.13 0.   0.43 0.16]
 [0.48 0.08 0.1  0.53 0.55]
 [0.6  0.   0.21 0.99 0.28]]


In [6]:
# Sélectionner la deuxième ligne
array_2d = np.array([[21, 22, 23, 22, 22],
                     [20, 21, 22, 23, 24],
                     [21, 22, 23, 22, 22]])

second_row = array_2d[1]
print(second_row)

[20 21 22 23 24]


In [7]:
# Inverser l'ordre des éléments
array_to_reverse = np.arange(10)
reversed_array = array_to_reverse[::-1]
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


In [8]:
# Créer une matrice d'identité 4x4
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Trouver la somme et la moyenne
array_agg = np.arange(10) # Utilisation du tableau de l'exercice 1
somme = np.sum(array_agg)
moyenne = np.mean(array_agg)

print(f"Sum: {somme}, Average: {moyenne}")

Sum: 45, Average: 4.5


In [10]:
# Créer de 1 à 20 et redimensionner en 4x5
array_reshaped = np.arange(1, 21).reshape(4, 5)
print(array_reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [11]:
# Extraire les nombres impairs
array_base = np.arange(10)
odd_numbers = array_base[array_base % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
