In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.4.6


In [4]:
tableau = np.array([1, 2, 3,4,5,6,7,8,9,10])
print(tableau[4])

5


In [6]:
print(tableau[2:8])

[3 4 5 6 7 8]


In [9]:
rand= np.random.randint(10,50,6)
print(rand[rand>30])

[32 32 49 45]


In [12]:
indices=[1,3,5]
print(tableau[indices])

[2 4 6]


In [13]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new


array([5, 1, 2, 7, 4, 3, 6])

In [22]:
x=np.arange(1,10,2)
x[2]=999
x


array([  1,   3, 999,   7,   9])

In [23]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [43]:
import numpy as np
from scipy import stats

# Sample data (engagement time in minutes)
sample_data = np.array(np.arange(15, 20) )  # Example data
# Performing a one-sample t-test
t_statistic, p_value = stats.ttest_1samp(sample_data, 15)

# Interpreting the result
alpha = 0.05  # Significance level
if p_value < alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")




Reject the null hypothesis
